# -*- coding: utf-8 -*-
"""Groupwork1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/tackulus/206428/blob/main/Groupwork1.ipynb
"""

ciphertext = "G TGYZ FA TOF WVTVZQ (WSGXYZQ HVWNZUQ): VT OGQ TSZ PZQT FA TVCZQ, VT OGQ TSZ OFXQT FA TVCZQ, VT OGQ TSZ GMZ FA OVQHFC, VT OGQ TSZ GMZ FA AFFYVQSUZQQ, VT OGQ TSZ ZKFWS FA PZYVZA, VT OGQ TSZ ZKFWS FA VUWXZHEYVTL, VT OGQ TSZ QZGQFU FA YVMST, VT OGQ TSZ QZGQFU FA HGXNUZQQ, VT OGQ TSZ QKXVUM FA SFKZ, VT OGQ TSZ OVUTZX FA HZQKGVX, OZ SGH ZJZXLTSVUM PZAFXZ EQ, OZ SGH UFTSVUM PZAFXZ EQ, OZ OZXZ GYY MFVUM HVXZWT TF SZGJZU, OZ OZXZ GYY MFVUM HVXZWT TSZ FT- SZX OGL — VU QSFXT, TSZ KZXVFH OGQ QF AGX YVNZ TSZ KXZQZUT KZXVFH, TSGT QFCZ FA VTQ UFVQVZQT GETSFXVTVZQ VUQVQTZH FU VTQ PZVUM XZWZVJZH, AFX MFFH FX AFX ZJVY, VU TSZ QEKZXYGTVJZ HZMXZZ FA WFCKGXVQFU FUYL."

dct = {chr(n): 0 for n in range(65, 91)}
for x in ciphertext:
    if x in dct:
        dct[x] += 1

decoder = {'A': "f",
           'B': "",
           'C': "m",
           'D': "",
           'E': "u",
           'F': "o",
           'G': "a",
           'H': "d",
           'I': "",
           'J': "v",
           'K': "p",
           'L': "y",
           'M': "g",
           'N': "k",
           'O': "w",
           'P': "b",
           'Q': "s",
           'R': "",
           'S': "h",
           'T': "t",
           'U': "n",
           'V': "i",
           'W': "c",
           'X': "r",
           'Y': "l",
           'Z': "e"}

plaintext = ""
for y in ciphertext:
    x = decoder[y] if y in decoder else y
    x = y if x == "" else x
    plaintext += x

print(plaintext)
